# Site settings
title: Allegra Via, PhD
contact: Allegra Via
email: allegra.via@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Allegra Via's website.
baseurl: "/website" # the subpath of your site, e.g. /blog/
url: "http://allegravia.github.io" # the base hostname & protocol for your site
twitter_username: elixir_ita
github_username: allegravia 

# Build settings

# I declare _sass as the sass directory, to ensure the Sass compiles correctly
sass:
  sass_dir: _sass

include: ['_pages']

markdown: kramdown
kramdown:
  input: GFM

# change server port to 3000
port: 3000

